blockchain/src/main/java/br/com/ideiasaleatorias/eleicaoonline/models/Ellection.java
package br.com.ideiasaleatorias.eleicaoonline.models;

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import br.com.ideiasaleatorias.eleicaoonline.security.SystemUser;

@Entity
public class Ellection {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	@NotBlank
	private String name;
	@NotNull
	private LocalDateTime endingTime;
	@ManyToOne
	@NotNull
	private SystemUser owner;

	/**
	 * @deprecated
	 */
	public Ellection() {

	}

	public Ellection(String name,LocalDateTime endingTime,SystemUser owner) {
		super();
		this.name = name;
		this.endingTime = endingTime;
		this.owner = owner;
	}
	
	public String getName() {
		return name;
	}
	
	public Integer getId() {
		return id;
	}

	public boolean isOwnedByUser(SystemUser possibleOwner) {
		return owner.equals(possibleOwner);
	}

}

blockchain/src/main/java/br/com/ideiasaleatorias/eleicaoonline/models/Voter.java
package br.com.ideiasaleatorias.eleicaoonline.models;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@Entity
public class Voter {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@NotBlank
	@Column(unique=true)	
	private String number;
	
	@ManyToOne
	@NotNull
	private Ellection ellection;
	
	private LocalDateTime approvedInstant;

	private boolean generatedTicket;
	
	/**
	 * @deprecated
	 */
	public Voter() {

	}

	public Voter(@NotBlank String number,Ellection ellection) {
		super();
		this.number = number;
		this.ellection = ellection;
	}
	
	public void approve(){
		if(approvedInstant != null){
			throw new IllegalStateException("Esse eleitor já foi aprovado para está eleição "+approvedInstant);
		}
		
		this.approvedInstant = LocalDateTime.now();		
	}
	
	public String getNumber() {
		return number;
	}
	
	public boolean isApproved(){
		return this.approvedInstant != null;
	}
	
	public Integer getId() {
		return id;
	}

	public Ellection getEllection() {
		return ellection;
	}

	public VoteTicket generateTicket() {
		if(this.generatedTicket || !this.isApproved()) {
			throw new IllegalStateException("ticket não pode ser gerado");
		}
		this.generatedTicket = true;
		return new VoteTicket(); 
	}
	
	public boolean isGeneratedTicket() {
		return generatedTicket;
	}
	
	
}

blockchain/src/main/java/br/com/ideiasaleatorias/eleicaoonline/controllers/EllectionsController.java
package br.com.ideiasaleatorias.eleicaoonline.controllers;

import javax.transaction.Transactional;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import br.com.ideiasaleatorias.eleicaoonline.controllers.forms.NewEllectionForm;
import br.com.ideiasaleatorias.eleicaoonline.daos.EllectionDao;
import br.com.ideiasaleatorias.eleicaoonline.infra.ViewMessages;
import br.com.ideiasaleatorias.eleicaoonline.security.SystemUser;

@Controller
@Transactional
public class EllectionsController {
	
	@Autowired
	private EllectionDao ellectionDao;

	@GetMapping("/ellections/form")
	public String form(Model model, NewEllectionForm form) {
		return "/ellection/form";
	}
	
	@PostMapping("/ellections")
	public String save(Model model, @Valid NewEllectionForm form, BindingResult bindingResult,
			RedirectAttributes redirectAttributes,@AuthenticationPrincipal SystemUser owner) {
		if (bindingResult.hasErrors()) {
			return form(model, form);
		}
		
		
		ellectionDao.save(form.toEllection(owner));

		ViewMessages.successFlash("eleição cadastrada com sucesso", redirectAttributes);
		return "redirect:/ellections/form";
	}
}

blockchain/src/main/java/br/com/ideiasaleatorias/eleicaoonline/controllers/RegisteredVotersController.java
package br.com.ideiasaleatorias.eleicaoonline.controllers;

import javax.transaction.Transactional;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import br.com.ideiasaleatorias.eleicaoonline.controllers.forms.SearchEllectionForm;
import br.com.ideiasaleatorias.eleicaoonline.daos.EllectionDao;
import br.com.ideiasaleatorias.eleicaoonline.daos.VoterDao;
import br.com.ideiasaleatorias.eleicaoonline.infra.ViewMessages;
import br.com.ideiasaleatorias.eleicaoonline.models.Voter;
import br.com.ideiasaleatorias.eleicaoonline.security.SystemUser;

@Controller
@Transactional
public class RegisteredVotersController {
	
	@Autowired
	private EllectionDao ellectionDao;
	@Autowired
	private VoterDao voterDao;

	@GetMapping("/registered")
	public String form(Model model,SearchEllectionForm form,@AuthenticationPrincipal SystemUser owner) {
		model.addAttribute("ellections", ellectionDao.findByOwnerId(owner.getId()));
		return "/ellection/registered-voters";
	}
	
	@GetMapping("/registered/ellection")
	public String search(Model model, SearchEllectionForm form,BindingResult result,@AuthenticationPrincipal SystemUser owner) {
		model.addAttribute("voters",voterDao.findAllByEllectionId(form.getEllectionId()));
		return form(model, form, owner);
	}
	
	@PostMapping("/registered/{voterId}/approve")
	public String approve(Model model,@PathVariable("voterId") Integer voterId,RedirectAttributes redirectAttributes) {
		
		Voter voter = voterDao.findById(voterId).get();
		voter.approve();
		
		ViewMessages.successFlash("eleitor liberado com sucesso", redirectAttributes);
		return "redirect:/registered/ellection?ellectionId="+voter.getEllection().getId();
	}
}

blockchain/src/main/java/br/com/ideiasaleatorias/eleicaoonline/controllers/VotingBoothController.java
package br.com.ideiasaleatorias.eleicaoonline.controllers;

import java.util.Optional;

import javax.transaction.Transactional;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import br.com.ideiasaleatorias.eleicaoonline.controllers.forms.ChooseElectionForm;
import br.com.ideiasaleatorias.eleicaoonline.controllers.forms.GenerateCodeForm;
import br.com.ideiasaleatorias.eleicaoonline.controllers.forms.VotingBoothForm;
import br.com.ideiasaleatorias.eleicaoonline.daos.CandidateDao;
import br.com.ideiasaleatorias.eleicaoonline.daos.EllectionDao;
import br.com.ideiasaleatorias.eleicaoonline.daos.VoteTicketDao;
import br.com.ideiasaleatorias.eleicaoonline.daos.VoterDao;
import br.com.ideiasaleatorias.eleicaoonline.infra.ViewMessages;
import br.com.ideiasaleatorias.eleicaoonline.models.Candidate;
import br.com.ideiasaleatorias.eleicaoonline.models.VoteTicket;
import br.com.ideiasaleatorias.eleicaoonline.models.Voter;
import br.com.ideiasaleatorias.eleicaoonline.service.VoterService;

@Controller
@Transactional
public class VotingBoothController {

	@Autowired
	private CandidateDao candidateDao;
	@Autowired
	private VoterDao voterDao;
	@Autowired
	private VoteTicketDao voteTicketDao;
	@Autowired
	@Qualifier("descentralizado")
	private VoterService voterService;
	@Autowired
	private EllectionDao ellectionDao;
	
	@GetMapping("/votingbooth/code/form")
	public String codeGeneratorForm(Model model, GenerateCodeForm form) {
		return "/ellection/generate-code-form";
	}
	
	@PostMapping("/votingbooth/code")
	public String generateTicket(Model model, @Valid GenerateCodeForm form, BindingResult bindingResult,
			RedirectAttributes redirectAttributes) {
		if (bindingResult.hasErrors()) {
			return codeGeneratorForm(model, form);
		}
		
		Optional<Voter> voter = voterDao.findByNumber(form.getVoterNumber());
		if(voter.isPresent() && voter.get().isApproved()){
			VoteTicket ticket = voteTicketDao.save(voter.get().generateTicket());			
			ViewMessages.successFlash("O seu código de votação é "+ticket.getUserNumber(), redirectAttributes);
			return "redirect:/votingbooth/code/form?ticketCode="+ticket.getUserNumber();
		}
		
		ViewMessages.error("o número passado está errado ou ainda não está liberado", model);
		return codeGeneratorForm(model, form);
		

	}
	
	@GetMapping("/votingbooth/choose/ellection/form")
	public String chooseEllectionForm(Model model, ChooseElectionForm form) {
		model.addAttribute("ellections", ellectionDao.findAll());
		return "/ellection/choose-ellection";
	}
	
	@GetMapping("/votingbooth/choose/ellection")
	public String methodName(Model model, @Valid ChooseElectionForm form, BindingResult bindingResult,
			RedirectAttributes redirectAttributes) {
		if (bindingResult.hasErrors()) {
			return chooseEllectionForm(model, form);
		}

		return "redirect:/votingbooth?ellectionId="+form.getEllectionId();
	}

	@GetMapping("/votingbooth")
	public String form(Model model, VotingBoothForm form) {
		model.addAttribute("candidates", candidateDao.findAllByEllectionId(form.getEllectionId()));
		return "/ellection/voting-booth";
	}

	@PostMapping("/votingbooth/vote")
	public String vote(Model model, @Valid VotingBoothForm form, BindingResult bindingResult,
			RedirectAttributes redirectAttributes) {

		if (bindingResult.hasErrors()) {
			return form(model, form);
		}

		
		Candidate candidate = candidateDao.findById(form.getCandidateId()).get();		
		voterService.execute(candidate,voteTicketDao.findByUserNumber(form.getTicketCode()).get());
		


		ViewMessages.successFlash("seu voto foi registrado com sucesso", redirectAttributes);
		return "redirect:/votingbooth?ellectionId="+form.getEllectionId();
	}
}

blockchain/src/main/webapp/WEB-INF/views/ellection/choose-ellection.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@include file="../../taglibs.jsp"%>

<sistema:template titulo="Dê o seu voto">
	
	<sistema:message/>
	<form:form action="/votingbooth/choose/ellection" modelAttribute="chooseElectionForm" method="get">
        <div class="col-md-8 col-sm-12 mx-auto common-margin-bottom">
                <div class="row common-margin-bottom">
                    <div class="form-group d-block col-12">
                        <label for="ellectionId">Eleição</label>
                        <form:select path="ellectionId" items="${ellections}" itemLabel="name" itemValue="id" class="custom-select custom-select-lg"/>
                        <form:errors path="ellectionId"/>
                    </div>
                </div>
         </div>         
         <div class="row">
             <button type="submit" class="btn btn-success col-md-6 col-sm-6 col-xs-6 mx-auto">
                 Votar
             </button>
         </div>		
	</form:form>
</sistema:template>

blockchain/src/main/webapp/WEB-INF/views/ellection/form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@include file="../../taglibs.jsp"%>
<sistema:template titulo="Cadastro de eleição">
	<sistema:message/>
	<form:form action="/ellections" method="post" modelAttribute="newEllectionForm">
        <div class="col-md-8 col-sm-12 mx-auto common-margin-bottom">
                <div class="row common-margin-bottom">
                    <div class="form-group d-block col-12">
                        <label for="name">Nome da eleição</label>
                        <form:input path="name" class="form-control" placeholder="nome da eleição"/>
                        <small id="name" class="form-text text-muted">Pense em um nome criativo.</small>
                        <form:errors path="name"/>
                    </div>
                </div>        
                <div class="row common-margin-bottom">
                    <div class="form-group d-block col-12">
                        <label for=endingTime>Data de fim</label>
                        <form:input path="endingTime" class="form-control" placeholder="ex:20/10/2018"/>
                        <small id="endingTime" class="form-text text-muted">não erre a data :)</small>
                        <form:errors path="endingTime"/>
                    </div>
                </div>    
                <div class="row">
                    <button type="submit" class="btn btn-success col-md-6 col-sm-6 col-xs-6 mx-auto">
                        Cadastrar eleição
                    </button>
                </div>                    
        </div>	
	</form:form>
</sistema:template>

blockchain/src/main/webapp/WEB-INF/views/ellection/generate-code-form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@include file="../../taglibs.jsp"%>
<sistema:template titulo="Gerar código de eleição">
	<sistema:message/>
	<form:form action="/votingbooth/code" modelAttribute="generateCodeForm">
        <div class="col-md-8 col-sm-12 mx-auto common-margin-bottom">
                <div class="row common-margin-bottom">
                    <div class="form-group d-block col-12">
                        <label for="voterNumber">Número de eleitor</label>
                        <form:input path="voterNumber" class="form-control" placeholder="seu número de eleitor"/>
                        <form:errors path="voterNumber"/>
                    </div>
                </div>
         </div>
         <div class="row">
             <button type="submit" class="btn btn-success col-md-6 col-sm-6 col-xs-6 mx-auto">
                 Gerar número de voto
             </button>
         </div>         			
	</form:form>
</sistema:template>

blockchain/src/main/webapp/WEB-INF/views/ellection/registered-voters.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <%@include file="../../taglibs.jsp"%>

<sistema:template titulo="Liberação de eleitores">


    <div class="container">
    	<sistema:message/>
        <form:form method="get" action="/registered/ellection" modelAttribute="searchEllectionForm">
            <div class="col-md-8 col-sm-12 mx-auto common-margin-bottom">
                <div class="row common-margin-bottom">
                    <div class="form-group d-block col-8">
	                    <form:select path="ellectionId" items="${ellections}" itemLabel="name" itemValue="id" class="custom-select custom-select-lg"/>
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">
                        Pesquisar
                        </button>
                    </div>
                </div>
                <div class="row">
                </div>
            </div>
        </form:form>
    </div>
    
    <div class="container">
        <h1>Eleitores para aprovação</h1>
        <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">identificador</th>
            <th scope="col">aprovado?</th>
            </tr>
        </thead>
        <tbody>
	        <c:forEach var="voter" items="${voters}">
	            <tr>
	                <td>${voter.number}</td>
					<c:if test="${voter.approved}">
						<td>aprovado</td>
					</c:if>	
					<c:if test="${!voter.approved}">
	                <td>
	                	<form:form action="/registered/${voter.id}/approve" method="post">
	                    	<button type="submit" class="btn btn-dark">Aprovar</button>
	                    </form:form>	                    
	                </td>					
					</c:if>                	                
	            </tr>
	         </c:forEach>
        </tbody>
        </table>
    </div>    
</sistema:template>

blockchain/src/main/webapp/WEB-INF/views/ellection/voting-booth.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@include file="../../taglibs.jsp"%>

<sistema:template titulo="Dê o seu voto">
	
	<sistema:message/>
	<form:form action="/votingbooth/vote" modelAttribute="votingBoothForm">
		<form:hidden path="ellectionId"/>				
		
        <div class="col-md-8 col-sm-12 mx-auto common-margin-bottom">
                <div class="row common-margin-bottom">
                    <div class="form-group d-block col-12">
                        <label for="ticketCode">Seu identificador</label>
                        <form:input path="ticketCode" class="form-control" placeholder="sua chave privada"/>
                        <form:errors path="ticketCode"/>
                    </div>
                </div>
         </div>
        <div class="col-md-8 col-sm-12 mx-auto common-margin-bottom">
                <div class="row common-margin-bottom">
                    <div class="form-group d-block col-12">
                        <label for="candidateId">Candidato</label>
                        <form:select path="candidateId" items="${candidates}" itemLabel="name" itemValue="id" class="custom-select custom-select-lg"/>
                        <form:errors path="candidateId"/>
                    </div>
                </div>
         </div>         
         <div class="row">
             <button type="submit" class="btn btn-success col-md-6 col-sm-6 col-xs-6 mx-auto">
                 Votar!
             </button>
         </div>		
	</form:form>
</sistema:template>